name: yujinkim02
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#fcf7d7'
    - '#3f3e4c'
    - '#6a656c'
    - '#b8a68e'
  brandStrength: 0.2841395540162921
  lightness: 0.08462113584391773
  saturation: 0.5962162134237587
  rhythmicContrast: 0.6294440052006394
purpose: []
