name: yujinkim02
favicon: null
layout_spectrum: 0.2437
typography_spectrum: 0.25472
title: 'Me too!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#fcf7d7'
    - '#3f3e4c'
    - '#6a656c'
    - '#b8a68e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
